# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e81d3713c38a5e9865c2523fddb5e1807cd72f975bddd9eb50bd03791c81f4aeb66237864fe03c95e88b79b62062738a0a6250b58a6f9a241bcb5eb7edce995c

test:
  secret_key_base: a1a7590943df6454616638d6a69f336c1d0058fc4d4ee88bc1a5948a2933fe9e0747077d207860537bc6edea7ea7d7af7d336c76eea165aa9dcead97ca6adc47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
